-- CreateTable
CREATE TABLE "Corgi" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "name" TEXT NOT NULL,
    "pets" INTEGER NOT NULL DEFAULT 0,
    "boops" INTEGER NOT NULL DEFAULT 0
);
