-- CreateTable
CREATE TABLE "Toy" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "name" TEXT NOT NULL,
    "corgiId" INTEGER NOT NULL,
    FOREIGN KEY ("corgiId") REFERENCES "Corgi" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
